import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom'; // Assuming you'll have a back button

// ================================================================================
// Main Component to be exported
// ================================================================================
const MimamsaPage = () => {
  // Animation Variants
  const fadeIn = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.8, ease: "easeOut" } }
  };

  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  return (
    <div className="bg-[#F8F5F2] text-slate-800 font-sans">
      {/* Hero Section */}
      <motion.section 
        className="relative h-[60vh] min-h-[400px] flex items-center justify-center text-white text-center px-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1 }}
      >
        <div className="absolute inset-0 z-0">
          <img 
            src="https://images.unsplash.com/photo-1621871254884-386bd615152a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmVkaWMlMjByaXR1YWx8ZW58MHx8MHx8fDA%3D" 
            alt="Vedic fire ritual (Yajna)"
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/40 to-transparent"></div>
        </div>
        <motion.div className="relative z-10" initial="hidden" animate="visible" variants={fadeIn}>
          <h1 className="text-5xl md:text-8xl font-serif tracking-wider uppercase">Mīmāṃsā</h1>
          <p className="mt-2 text-xl md:text-2xl text-amber-100/90 font-light">The Philosophy of Vedic Exegesis</p>
        </motion.div>
      </motion.section>

      {/* Main Content */}
      <div className="container mx-auto px-6 py-24 max-w-5xl">

        {/* Introduction to Ritual */}
        <motion.section className="mb-24 text-center" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={fadeIn}>
          <h2 className="text-4xl font-serif text-slate-900 mb-4">Upholding the Vedic Injunctions</h2>
          <p className="text-lg text-slate-600 leading-relaxed max-w-3xl mx-auto">
            Mīmāṃsā, founded by the sage Jaimini, is a school dedicated to the interpretation (**exegesis**) of the Vedas. Its primary goal is to establish the authority of the Vedas and provide a philosophical justification for observing the rituals (**Karma-kāṇḍa**) prescribed within them.
          </p>
        </motion.section>

        {/* Dharma & Apurva Section */}
        <motion.section className="grid md:grid-cols-2 gap-12 items-center mb-24" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={staggerContainer}>
          <motion.div variants={fadeIn} className="bg-white p-8 rounded-lg shadow-sm border border-slate-200/80">
            <h3 className="text-3xl font-serif text-orange-700 mb-3">Dharma (धर्म)</h3>
            <p className="text-slate-600 leading-relaxed">
              In Mīmāṃsā, **Dharma** is not an abstract moral code but the specific set of duties and rituals enjoined by the Vedas. The performance of these actions is considered the highest duty, leading to merit and desirable outcomes, such as attaining heaven (**Svarga**).
            </p>
          </motion.div>
          <motion.div variants={fadeIn} className="bg-white p-8 rounded-lg shadow-sm border border-slate-200/80">
            <h3 className="text-3xl font-serif text-cyan-700 mb-3">Apūrva (अपूर्व)</h3>
            <p className="text-slate-600 leading-relaxed">
              **Apūrva** is a unique concept meaning "unseen" or "unprecedented." It is the latent, metaphysical force generated by a correctly performed ritual. This force acts as a bridge, ensuring that the ritual's fruit materializes for the performer at a later time.
            </p>
          </motion.div>
        </motion.section>

        {/* The Authority of the Vedas Section */}
        <motion.section className="mb-24" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={fadeIn}>
          <div className="text-center mb-12">
            <h2 className="text-4xl font-serif text-slate-900 mb-4">The Infallible Authority of the Vedas</h2>
            <p className="text-lg text-slate-600 leading-relaxed max-w-3xl mx-auto">
              To justify the importance of ritual, Mīmāṃsā establishes the absolute authority of the Vedas. They are considered eternal, unauthored, and intrinsically valid, requiring no external justification.
            </p>
          </div>
          <div className="bg-white p-8 rounded-lg shadow-sm border max-w-4xl mx-auto text-center">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-orange-50 p-6 rounded-lg border border-orange-200">
                    <h5 className="font-bold text-lg mb-2">Apauruṣeya</h5>
                    <p className="text-sm text-slate-600">"Not of human origin." The Vedas are believed to be authorless and eternal, free from the errors and biases of human authors.</p>
                </div>
                <div className="bg-cyan-50 p-6 rounded-lg border border-cyan-200">
                    <h5 className="font-bold text-lg mb-2">Svataḥ Prāmāṇya</h5>
                    <p className="text-sm text-slate-600">"Self-validity." All knowledge, especially Vedic knowledge, is considered true on its own accord. Falsity, not truth, is what needs to be proven.</p>
                </div>
            </div>
          </div>
        </motion.section>

        {/* Path to Liberation Section */}
        <motion.section className="text-center" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.5 }} variants={fadeIn}>
          <h2 className="text-4xl font-serif text-slate-900 mb-4">Svarga and Mokṣa: The Fruits of Action</h2>
          <p className="text-lg text-slate-600 leading-relaxed max-w-3xl mx-auto">
            The primary goal of Mīmāṃsā is the attainment of **Svarga** (heaven) through the precise execution of Vedic rituals. Later Mīmāṃsā thinkers also incorporated the goal of **Mokṣa** (liberation), arguing that it could be achieved by performing one's obligatory duties without any attachment to the results, thereby exhausting past karma and preventing the accumulation of new karma.
          </p>
          <Link to="/explore" className="mt-10 inline-block bg-orange-600 text-white font-bold tracking-widest uppercase py-3 px-8 text-sm hover:bg-orange-700 transition-all duration-300 rounded-sm">
            Back to Explore
          </Link>
        </motion.section>

      </div>
    </div>
  );
};

export default MimamsaPage;