import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeftIcon, ChevronDownIcon } from "@heroicons/react/24/outline";
import ScrollToTop from "../../Components/ScrollToTop";
import mimamsaImg from "../Schools-images/mimamsa_hero.png";

const MimamsaPage = () => {
  const [activeConcept, setActiveConcept] = useState(null);

  const fadeIn = {
    hidden: { opacity: 0, y: 30 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.8, ease: "easeOut" },
    },
  };
  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.2 } },
  };

  const concepts = [
    {
      name: "Dharma",
      desc: "The primary focus. Defined as the duties and rituals prescribed by the Vedas, which maintain the order of the cosmos.",
      color: "from-red-600 to-orange-500",
    },
    {
      name: "Śabda-nityatva",
      desc: "The Eternity of Sound. Mimamsa asserts that the relationship between a word and its meaning is eternal and uncreated.",
      color: "from-amber-500 to-yellow-400",
    },
    {
      name: "Apūrva",
      desc: "The Latent Fruit. The invisible, spiritual force generated by a correctly performed ritual that produces its results in the future.",
      color: "from-purple-500 to-indigo-500",
    },
    {
      name: "Vidhi",
      desc: "Injunction. The Vedic commands that impel a person to action. Mimamsa is a philosophy of 'action' (Karma).",
      color: "from-blue-500 to-cyan-500",
    },
    {
      name: "Arthavāda",
      desc: "Explanatory passages in the Vedas that praise a ritual or decry its omission, serving to motivate the practitioner.",
      color: "from-emerald-500 to-teal-500",
    },
  ];

  return (
    <div className="bg-[#fff1f1] dark:bg-[#0f0a0a] text-slate-800 dark:text-slate-200 transition-colors duration-300 font-sans selection:bg-red-500/30">
      <ScrollToTop />

      {/* Hero */}
      <motion.section
        className="relative min-h-[85vh] flex flex-col items-center justify-center text-center px-4 overflow-hidden"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1.2 }}
      >
        <div className="absolute inset-0 z-0">
          <img
            src={mimamsaImg}
            alt="The sacred Vedic sacrifice"
            className="w-full h-full object-cover opacity-60"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-[#fff1f1] via-[#fff1f1]/80 to-transparent dark:from-[#0f0a0a] dark:via-[#0f0a0a]/80 dark:to-transparent"></div>
          <motion.div
            className="absolute top-1/4 left-1/4 w-[450px] h-[450px] bg-red-500/10 rounded-full blur-[130px]"
            animate={{ scale: [1, 1.2, 1], opacity: [0.2, 0.4, 0.2] }}
            transition={{ duration: 8, repeat: Infinity }}
          />
          <motion.div
            className="absolute bottom-1/4 right-1/4 w-[450px] h-[450px] bg-amber-500/10 rounded-full blur-[130px]"
            animate={{ scale: [1, 1.3, 1], opacity: [0.2, 0.5, 0.2] }}
            transition={{ duration: 10, repeat: Infinity, delay: 1 }}
          />
        </div>
        <motion.div
          className="relative z-10 max-w-4xl mx-auto"
          initial="hidden"
          animate="visible"
          variants={staggerContainer}
        >
          <motion.div variants={fadeIn} className="mb-6 flex justify-center">
            <span className="px-4 py-1.5 rounded-full border border-red-500/30 bg-red-500/10 text-red-700 dark:text-red-400 text-sm font-semibold tracking-widest uppercase">
              Founded by Sage Jaimini
            </span>
          </motion.div>
          <motion.h1
            variants={fadeIn}
            className="text-6xl md:text-8xl lg:text-9xl font-serif tracking-tight text-transparent bg-clip-text bg-gradient-to-b from-slate-900 via-slate-700 to-slate-500 dark:from-white dark:via-slate-200 dark:to-slate-500 mb-6"
          >
            Mīmāṃsā
          </motion.h1>
          <motion.p
            variants={fadeIn}
            className="text-xl md:text-3xl text-slate-600 dark:text-slate-400 font-light tracking-wide mb-12"
          >
            The Sovereignty of the Ritual Word
          </motion.p>
          <motion.div variants={fadeIn}>
            <p className="text-lg md:text-xl text-slate-700 dark:text-slate-300 leading-relaxed max-w-2xl mx-auto font-serif italic">
              "The Veda is the only authority on Dharma, and its words are
              eternal." <br /> — Mīmāṃsā Sūtras
            </p>
          </motion.div>
        </motion.div>
        <motion.div
          className="absolute bottom-10 left-1/2 -translate-x-1/2 text-slate-500 flex flex-col items-center gap-2"
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          <span className="text-sm tracking-widest uppercase">
            Uphold the Order
          </span>
          <ChevronDownIcon className="w-5 h-5" />
        </motion.div>
      </motion.section>

      <div className="container mx-auto px-6 py-24 max-w-6xl">
        {/* Introduction */}
        <motion.section
          className="mb-32 bg-white dark:bg-[#120a0a] p-10 md:p-16 rounded-[40px] border border-slate-200 dark:border-slate-800 shadow-xl dark:shadow-2xl"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.3 }}
          variants={fadeIn}
        >
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-sm text-red-600 dark:text-red-500 font-bold tracking-[0.3em] uppercase mb-4">
                The Path of Action
              </h2>
              <h3 className="text-4xl md:text-5xl font-serif text-slate-900 dark:text-white mb-8 leading-tight">
                Dharma through Duty
              </h3>
              <p className="text-lg text-slate-600 dark:text-slate-400 leading-relaxed mb-6">
                Mīmāṃsā is the school of hermeneutics and ritualism. It believes
                that the universe is governed by an eternal law, and the key to
                harmony lies in the precise execution of Vedic rituals.
              </p>
              <p className="text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
                For the Mīmāṃsaka, the Vedas are not the work of any author
                (Apauruṣeyā); they are the fabric of reality itself. By
                contemplating the ritual word and acting upon it, one aligns
                with the cosmic order and secures both worldly prosperity and
                spiritual merit.
              </p>
            </div>
            <div className="relative h-[450px] w-full rounded-3xl overflow-hidden shadow-xl dark:shadow-[0_0_50px_rgba(239,68,68,0.1)] border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-[#0a0505] flex items-center justify-center p-12">
              <div className="relative w-full h-full flex items-center justify-center">
                <div className="absolute bottom-1/4 w-32 h-8 bg-orange-950/40 blur-xl rounded-full"></div>
                {[...Array(12)].map((_, i) => (
                  <motion.div
                    key={i}
                    className="absolute bottom-1/4 w-12 h-24 bg-gradient-to-t from-orange-600 via-red-500 to-transparent rounded-full blur-lg"
                    initial={{ opacity: 0, y: 0, scale: 1 }}
                    animate={{
                      opacity: [0, 0.6, 0.4, 0],
                      y: [-20, -150 - i * 10],
                      x: [
                        (i - 6) * 5,
                        (i - 6) * 10 + (Math.random() - 0.5) * 40,
                      ],
                      scale: [1, 1.5, 0.5],
                      rotate: [(i - 6) * 5, (i - 6) * 10],
                    }}
                    transition={{
                      duration: 2 + Math.random() * 2,
                      repeat: Infinity,
                      delay: i * 0.3,
                      ease: "easeOut",
                    }}
                  />
                ))}
                <motion.div
                  className="absolute bottom-1/4 w-16 h-40 bg-gradient-to-t from-yellow-400 via-orange-500 to-transparent rounded-full blur-xl"
                  animate={{ scaleY: [1, 1.2, 1], opacity: [0.4, 0.7, 0.4] }}
                  transition={{ duration: 1, repeat: Infinity }}
                />
                <div className="relative z-10 flex flex-col items-center">
                  <span className="text-7xl font-serif text-slate-700 dark:text-white opacity-40 drop-shadow-[0_0_30px_rgba(239,68,68,0.6)] mb-2">
                    यज्ञ
                  </span>
                  <span className="text-xs tracking-[0.4em] text-red-600 dark:text-red-500/60 uppercase font-bold">
                    The Holy Sacrifice
                  </span>
                </div>
                {[...Array(15)].map((_, i) => (
                  <motion.div
                    key={`ember-${i}`}
                    className="absolute bottom-1/4 w-1 h-1 bg-yellow-400 rounded-full"
                    animate={{
                      y: -250 - Math.random() * 100,
                      x: (Math.random() - 0.5) * 150,
                      opacity: [0, 1, 1, 0],
                      scale: [1, 1.5, 0],
                    }}
                    transition={{
                      duration: 3 + Math.random() * 2,
                      repeat: Infinity,
                      delay: Math.random() * 5,
                    }}
                  />
                ))}
              </div>
            </div>
          </div>
        </motion.section>

        {/* Concepts */}
        <motion.section
          className="mb-32"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.1 }}
          variants={fadeIn}
        >
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-serif text-slate-900 dark:text-white mb-6">
              The Ritual Framework
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
              How Mīmāṃsā explains the power of the word and the mechanism of
              spiritual merit.
            </p>
          </div>
          <div className="grid lg:grid-cols-2 gap-12 items-start">
            <div className="space-y-3">
              {concepts.map((concept, index) => (
                <motion.div
                  key={index}
                  className={`p-5 rounded-xl cursor-pointer border transition-all duration-300 ${activeConcept === index ? "bg-red-50 dark:bg-slate-800/80 border-red-500 dark:border-red-600 shadow-lg" : "bg-white dark:bg-slate-900/40 border-slate-200 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50"}`}
                  onClick={() =>
                    setActiveConcept(index === activeConcept ? null : index)
                  }
                  whileHover={{ x: 5 }}
                >
                  <div className="flex justify-between items-center">
                    <h4 className="text-xl font-serif text-slate-800 dark:text-slate-200">
                      <span className="text-slate-400 dark:text-slate-600 font-mono text-sm mr-4">
                        {String(index + 1).padStart(2, "0")}
                      </span>
                      {concept.name}
                    </h4>
                    <ChevronDownIcon
                      className={`w-5 h-5 text-slate-400 transition-transform duration-300 ${activeConcept === index ? "rotate-180" : ""}`}
                    />
                  </div>
                  <AnimatePresence>
                    {activeConcept === index && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <p className="mt-4 text-slate-600 dark:text-slate-400 leading-relaxed pl-10 border-l-2 border-red-500/50 ml-2 py-1">
                          {concept.desc}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              ))}
            </div>
            <div className="sticky top-32 h-[500px] bg-slate-50 dark:bg-[#120a0a] rounded-3xl border border-slate-200 dark:border-slate-800 hidden lg:flex items-center justify-center p-8 flex-col relative overflow-hidden shadow-xl dark:shadow-2xl">
              {activeConcept === null ? (
                <div className="text-center">
                  <div className="w-24 h-24 mx-auto border border-red-600 dark:border-red-700 rounded-full flex items-center justify-center mb-6 animate-[pulse_4s_infinite]">
                    <div className="w-2 h-2 bg-red-500 dark:bg-red-400 rounded-full shadow-[0_0_15px_#ef4444]"></div>
                  </div>
                  <h3 className="text-2xl font-serif text-slate-700 dark:text-slate-300 mb-2">
                    The Sacred Echo
                  </h3>
                  <p className="text-slate-500 max-w-xs">
                    Select a concept to see how Mīmāṃsā translates Vedic sounds
                    into cosmic actions.
                  </p>
                </div>
              ) : (
                <motion.div
                  key={activeConcept}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="text-center z-10"
                >
                  <div
                    className={`w-40 h-40 mx-auto rounded-full bg-gradient-to-br ${concepts[activeConcept].color} mb-8 shadow-lg opacity-70 blur-[2px]`}
                  ></div>
                  <div className="absolute inset-0 flex items-center justify-center pointer-events-none z-20">
                    <h3 className="text-5xl font-serif text-slate-900 dark:text-white drop-shadow-[0_4px_8px_rgba(0,0,0,0.3)]">
                      {concepts[activeConcept].name}
                    </h3>
                  </div>
                  <p className="text-xl text-slate-700 dark:text-slate-300 max-w-md mx-auto mt-24 leading-relaxed bg-white/90 dark:bg-[#120a0a]/90 p-8 rounded-xl backdrop-blur-md border border-slate-200 dark:border-slate-800 shadow-xl dark:shadow-2xl">
                    {concepts[activeConcept].desc}
                  </p>
                </motion.div>
              )}
            </div>
          </div>
        </motion.section>

        {/* Liberation */}
        <motion.section
          className="relative py-20 px-8 md:px-16 bg-gradient-to-r from-red-100 to-orange-100 dark:from-red-900/20 dark:to-orange-900/20 rounded-3xl border border-red-200 dark:border-slate-700/50 text-center overflow-hidden"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.3 }}
          variants={fadeIn}
        >
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-red-500 via-orange-500 to-amber-500"></div>
          <h2 className="text-3xl md:text-5xl font-serif text-slate-900 dark:text-white mb-6">
            Apūrva: The Inevitable Reward
          </h2>
          <p className="text-lg md:text-xl text-slate-700 dark:text-slate-300 mb-10 max-w-3xl mx-auto leading-relaxed">
            Mīmāṃsā focuses on <strong>Abhyudaya</strong> (worldly wealth and
            heavenly bliss) through the performance of ritual. It posits that
            every act of Dharma leaves a residue (Apūrva) that matures into its
            promised fruit.
          </p>
          <p className="text-lg text-slate-600 dark:text-slate-400 mb-12 max-w-3xl mx-auto leading-relaxed">
            While earlier Mīmāṃsā stopped at the attainment of heaven, later
            thinkers evolved the concept of <strong>Niḥśreyasa</strong>{" "}
            (Liberation). This is achieved when one performs rituals without the
            desire for fruits, exhausting all past karma and allowing the soul
            to remain in its natural, painless state.
          </p>
          <Link
            to="/explore"
            className="inline-flex items-center gap-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-bold px-8 py-4 rounded-full hover:bg-slate-700 dark:hover:bg-slate-200 transition-colors shadow-lg"
          >
            <ArrowLeftIcon className="w-5 h-5" />
            Continue the Ritual
          </Link>
        </motion.section>
      </div>
    </div>
  );
};

export default MimamsaPage;
